[tool.poetry]
name = "django-nestedquery"
version = "0.1.0"
description = "Django Nested Query"
authors = ["Simage <simage@gmail.com>"]
packages = [
    { include = "nestedquery" },
]


[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1"

